export const storyData = [
    {
      id: "1",
      imgUrl: "https://img.freepik.com/free-psd/digital-marketing-agency-corporate-facebook-instagram-story-template_106176-502.jpg?size=626&ext=jpg&ga=GA1.1.918059691.1683563068&semt=ais",
      title: "Fish & Meat",
      personName: "Faruq Hasan",
      subTitleTwo: "Meat",
    },
    {
      id: "2",
      imgUrl: "https://img.freepik.com/free-psd/social-media-instgram-template_125755-892.jpg?w=360&t=st=1687273117~exp=1687273717~hmac=f08ace991cb2c10ceabad4314597a8f30b4af9bb79610c76d40586f2087b86f3",
      title: "Fruits & Vegetables",
      personName: "Tamal Sen",
      subTitleTwo: "Fresh Fruits",
      subTitleThree: "Fresh Vegetables",
    },
    {
      id: "3",
      imgUrl: "https://images.pexels.com/photos/5601140/pexels-photo-5601140.jpeg?auto=compress&cs=tinysrgb&w=600",
      title: "Fresh Seafood",
      personName: "Nishi Roy",
    },
    {
      id: "4",
      imgUrl: "https://img.freepik.com/free-psd/vertical-poster-with-pregnant-woman_23-2148758291.jpg?t=st=1687273117~exp=1687273717~hmac=30a514b7e9299d184e927742c4ab88fc86db568ad0a665dc8accead17d16500c",
      title: "Cooking Essentials",
      personName: "Sadiya Jaman",
      subTitleTwo: "",
      subTitleThree: "Flour",
    },
    {
      id: "5",
      imgUrl: "https://images.pexels.com/photos/10845717/pexels-photo-10845717.jpeg?auto=compress&cs=tinysrgb&w=600",
      title: "Breakfast",
      personName: "Ashik Khan",
      subTitleTwo: "Cereal",
    },
    {
      id: "6",
      imgUrl: "https://i.stack.imgur.com/vmNdT.jpg",
      title: "Drink",
      personName: "Rahul Dutta",
      subTitleTwo: "",
      subTitleThree: "Juice",
    },
    {
      id: "7",
      imgUrl: "https://i.stack.imgur.com/vmNdT.jpg",
      title: "Milk & Diary",
      personName: "Dairy",
      subTitleTwo: "Ice Cream",
      subTitleThree: "Butter & Ghee",
    },
    {
      id: "8",
      imgUrl: "https://i.stack.imgur.com/vmNdT.jpg",
      title: "Organic Food",
      personName: "Organic Food",
    },
    {
      id: "9",
      imgUrl: "https://i.stack.imgur.com/vmNdT.jpg",
      title: "Honey",
      personName: "Honey",
    },
    {
      id: "10",
      imgUrl: "https://i.stack.imgur.com/vmNdT.jpg",
      title: "Sauces & Pickles",
      personName: "Sauces",
      subTitleTwo: "Pickles & Condiments",
    },
    {
      id: "11",
      imgUrl: "https://i.stack.imgur.com/vmNdT.jpg",
      title: "Jam & Jelly",
      personName: "Jam & Jelly",
    },
    {
      id: "12",
      imgUrl: "https://i.stack.imgur.com/vmNdT.jpg",
      title: "Snacks & Instant",
      personName: "Chocolate",
      subTitleTwo: "Chips & Nuts",
      subTitleThree: "Canned Food",
    },
    {
      id: "13",
      imgUrl: "https://i.stack.imgur.com/vmNdT.jpg",
      title: "Biscuits & Cakes",
      personName: "Cakes",
      subTitleTwo: "Biscuits",
    },
    {
      id: "14",
      imgUrl: "https://i.stack.imgur.com/vmNdT.jpg",
      title: "Household Tools",
      personName: "Cleaner",
      subTitleTwo: "Laundry",
      subTitleThree: "Air Freshener",
    },
    {
      id: "15",
      imgUrl: "https://i.stack.imgur.com/vmNdT.jpg",
      title: "Baby Care",
      personName: "Baby Food",
      subTitleTwo: "Baby Accessories",
    },
    {
      id: "16",
      imgUrl: "https://i.stack.imgur.com/vmNdT.jpg",
      title: "Pet Care",
      personName: "Cat Care",
      subTitleTwo: "Dog Care",
      subTitleThree: "Bird Care",
    },
    {
      id: "17",
      imgUrl: "https://i.stack.imgur.com/vmNdT.jpg",
      title: "Beauty & Health",
      personName: "Bath",
      subTitleTwo: "Cosmetics",
      subTitleThree: "Oral Cares",
    },
    {
      id: "18",
      imgUrl: "https://i.stack.imgur.com/vmNdT.jpg",
      title: "Sports & Fitness",
      personName: "Sports",
      subTitleTwo: "Fitness",
    },
  ];